Set info_request in the template as it's no longer passed in via locals
Fixes error:

undefined local variable or method `info_request' for #<#<Class>